#ifndef PREFERENCE_H
#define PREFERENCE_H

enum PREFERENCES {
    LOCATIONS,
    SAVE_LOCATION,
    IMAGE_FORMAT,
    TEXT_ITEM_FONT,
    ITEM_COLOR,
    INTERFACE_BG_COLOR,
    TO_TRAY_ONCLOSE,
    TOGGLE_TRAY_ICON,
    TO_TRAY_ON_START,
    UPDATE_ON_START
};

#endif // PREFERENCE_H
